# Generated by Django 2.1.4 on 2019-01-04 20:18

import apps.demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.demo.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
